# Generated by Django 6.0.2 on 2026-03-29 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_contacto_curso_inscripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['orden', 'titulo']},
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='progreso',
        ),
        migrations.AddField(
            model_name='curso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/'),
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='plataforma.curso')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='plataforma.modulo')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('video_url', '🎬 Video (URL / YouTube)'), ('video_archivo', '📹 Video (Archivo subido)'), ('pdf', '📄 Archivo PDF'), ('texto', '📝 Texto / Descripción')], max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('es_gratis', models.BooleanField(default=False, help_text='Visible sin inscripción')),
                ('video_url', models.URLField(blank=True, help_text='URL de YouTube o cualquier video', null=True)),
                ('video_archivo', models.FileField(blank=True, null=True, upload_to='clases/videos/')),
                ('pdf_archivo', models.FileField(blank=True, null=True, upload_to='clases/pdfs/')),
                ('texto', models.TextField(blank=True, help_text='Contenido en texto o HTML', null=True)),
                ('duracion_minutos', models.PositiveIntegerField(default=0, help_text='Duración en minutos (opcional)')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='plataforma.seccion')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.clase')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='plataforma.inscripcion')),
            ],
            options={
                'unique_together': {('inscripcion', 'clase')},
            },
        ),
    ]
