# Generated by Django 6.0.2 on 2026-03-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_alter_curso_options_remove_inscripcion_progreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='categoria',
            field=models.CharField(blank=True, help_text='Ej: Electrónica, IoT, CAD', max_length=100),
        ),
        migrations.AddField(
            model_name='curso',
            name='descripcion_corta',
            field=models.CharField(blank=True, help_text='Texto corto para la tarjeta del catálogo', max_length=200),
        ),
    ]
