# Generated by Django 6.0.2 on 2026-06-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_curso_categoria_curso_descripcion_corta'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='anticipo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto del anticipo para apartar lugar en MXN', max_digits=10),
        ),
        migrations.AddField(
            model_name='curso',
            name='cupo_maximo',
            field=models.PositiveIntegerField(default=8, help_text='Número máximo de alumnos por grupo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='descripcion_larga',
            field=models.TextField(blank=True, help_text='Descripción completa para la página del curso (soporta saltos de línea)'),
        ),
        migrations.AddField(
            model_name='curso',
            name='dirigido_a',
            field=models.CharField(blank=True, help_text='Ej: Estudiantes, egresados y público general', max_length=300),
        ),
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.CharField(blank=True, help_text='Ej: 8 horas — 2 días × 4 horas', max_length=100),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_proxima',
            field=models.CharField(blank=True, help_text='Ej: 30 jun & 1 jul 2025 · 4:00 pm – 8:00 pm', max_length=200),
        ),
        migrations.AddField(
            model_name='curso',
            name='modalidad',
            field=models.CharField(blank=True, help_text='Ej: Presencial', max_length=100),
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.CharField(blank=True, help_text='Ej: Desde cero (requiere manejo básico de PC)', max_length=100),
        ),
        migrations.AddField(
            model_name='curso',
            name='precio_descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio con descuento en MXN (0 = no mostrar)', max_digits=10),
        ),
        migrations.AddField(
            model_name='curso',
            name='precio_descuento_label',
            field=models.CharField(blank=True, help_text='Ej: Alumnos & Egresados UPBC — 20% dto.', max_length=150),
        ),
        migrations.AddField(
            model_name='curso',
            name='precio_general',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio público general en MXN', max_digits=10),
        ),
        migrations.AddField(
            model_name='curso',
            name='whatsapp_mensaje',
            field=models.CharField(blank=True, help_text='Mensaje pre-llenado. Deja vacío para usar el mensaje automático con el nombre del curso.', max_length=400),
        ),
        migrations.AddField(
            model_name='curso',
            name='whatsapp_numero',
            field=models.CharField(blank=True, default='5216861373064', help_text='Número con clave de país sin + ni espacios. Ej: 5216861373064', max_length=20),
        ),
    ]
