# Generated by Django 6.0.2 on 2026-06-03 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_curso_anticipo_curso_cupo_maximo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clase',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clase',
            name='es_gratis',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clase',
            name='texto',
            field=models.TextField(blank=True, help_text='Contenido en texto plano — NO usar |safe en templates sin sanitizar', null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL de YouTube u otro video (solo HTTPS)', null=True, validators=[django.core.validators.URLValidator(schemes=['https'])]),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='curso',
            name='anticipo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='cupo_maximo',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion_corta',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion_larga',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='dirigido_a',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_proxima',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='curso',
            name='modalidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='precio_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='curso',
            name='precio_descuento_label',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='curso',
            name='precio_general',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='curso',
            name='whatsapp_mensaje',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='curso',
            name='whatsapp_numero',
            field=models.CharField(blank=True, help_text='Número con clave de país sin + ni espacios. Ej: 5216861373064', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Esperando Aprobación'), ('aprobado', 'Activo'), ('cancelado', 'Cancelado'), ('bloqueado', 'Bloqueado')], default='pendiente', max_length=20),
        ),
    ]
