# Generated by Django 6.0.2 on 2026-06-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_contacto_leido_alter_clase_duracion_minutos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='clase',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='whatsapp_numero',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
