# Generated by Django 6.0.2 on 2026-06-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_contacto_telefono_alter_clase_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='stripe_payment_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link de pago Stripe'),
        ),
    ]
